"""initial migration

Revision ID: e84009997034
Revises: 
Create Date: 2024-09-07 17:09:08.583036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84009997034'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_services_id'), 'services', ['id'], unique=False, schema='public')
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['public.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_keys_id'), 'keys', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_keys_id'), table_name='keys', schema='public')
    op.drop_table('keys', schema='public')
    op.drop_index(op.f('ix_public_services_id'), table_name='services', schema='public')
    op.drop_table('services', schema='public')
    # ### end Alembic commands ###
